### ISSUE TITLE
Autobuy not working

### ISSUE THREAD

**Issue by outgaze** [screret/BetterNEC#1]
Autobuy doesn't work it just opens the window it doesn't attempt to buy the item though.

**Comment by screret** [comment]
i can't test this right now, but i know the issue.
it's that the system's clicking, before the containers have had a chance to load. try the patch below:
[BetterNEC-1.0.1.1-all.jar.zip](https://github.com/screret/BetterNEC/files/8114305/BetterNEC-1.0.1.1-all.jar.zip)
.

**Comment by outgaze** [comment]
it's still failing to autobuy lol.

**Comment by screret** [comment]
does it get into another screen from the buy menu now?

**Comment by outmaneuver** [comment]
> does it get into another screen from the buy menu now?

Uh no the function works correctly it opens the auction just doesn't do the clicking or attempt to buy.

**Comment by outmaneuver** [comment]
It just does the /viewauction part but afterwards nothing...

**Comment by screret** [comment]
try the newest release. i think i had the slot numbers mixed up.

**Comment by outgaze** [comment]
Somehow, something broke I don't personally think it's cause of the autoflip feature as it doesn't change anything whether it's on or off but... I'm now not getting any flips meanwhile i tried running 2-3 different auction sniping mods along with BetterNEC and they were getting flips and snipes. Could be your new method of calculating profits? Also cause of that I can't test the autoflip function as BetterNEC isn't outputting any flips.

**Comment by outgaze** [comment]
I've literally ran it with 20m purse for 6-10 hours straight with the lowest settings for demand and profit and it's just not outputting anything.

**Comment by screret** [comment]
goddamnit back to debugging

**Comment by outgaze** [comment]
> goddamnit back to debugging

Now it is outputting flips but autobuy is not working still.

**Comment by outgaze** [comment]
And after all that time it still doesn't work, it just doesn't do the clicks bro lol

**Comment by screret** [comment]
Bitch i hadn't played skyblock in 3 months when u sent that comment
